[project]
name = "set8"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fpdf2>=2.8.3",
    "inflect>=7.5.0",
    "pillow>=11.3.0",
]

[dependency-groups]
dev = [
    "pylint>=3.3.7",
    "pytest>=8.4.1",
]
